export const metadata = {
  title: "Dashboard",
  description: "Generated by Dashboard  ",
};

export default function DashboardLayout({ children }) {
  return (
    <section>
      <nav>Add to cart</nav>
      {children}
    </section>
  );
}
